Repository Hammerspoon/hammerspoon, pull requests merged in 2021-03, with the labels that each got.

#2691 Rewrite hs.notify to remove memory leaks
  extensions/notify/internal.m
Labels: pr-fix

#2512 Added hs.eventtap.event.newGesture()
  Hammerspoon.xcodeproj/project.pbxproj
  extensions/eventtap/IOHIDEventData.h
  extensions/eventtap/IOHIDEventTypes.h
  extensions/eventtap/LICENSE.md
  extensions/eventtap/TouchEvents.c
  extensions/eventtap/TouchEvents.h
  extensions/eventtap/event.m
  extensions/eventtap/init.lua
Labels: pr-feature

#2493 Add method to hs.eventtap.event to capture touch data for events of type NSEventTypeGesture (29)
  extensions/eventtap/event.m
  extensions/eventtap/eventtap_event.h
  extensions/eventtap/init.lua
  extensions/eventtap/internal.m
Labels: pr-feature

#2694 Add a libraryName argument to registerLibrary for future use
  Hammerspoon Tests/HScoresetup.m
  Hammerspoon/MJLua.m
  LuaSkin/LuaSkin/Skin.h
  LuaSkin/LuaSkin/Skin.m
  LuaSkin/LuaSkinTests/LuaSkinTests.m
  extensions/application/internal.m
  extensions/audiodevice/watcher.m
  extensions/base64/internal.m
  extensions/battery/internal.m
  extensions/brightness/internal.m
  extensions/caffeinate/internal.m
  extensions/canvas/matrix_internal.m
  extensions/console/internal.m
  extensions/crash/internal.m
  extensions/dialog/internal.m
  extensions/distributednotifications/internal.m
  extensions/doc/internal.m
  extensions/doc/markdown.m
  extensions/dockicon/internal.m
  extensions/drawing/color/internal.m
  extensions/fs/xattr.m
  extensions/hash/internal.m
  extensions/hid/internal.m
  extensions/host/internal.m
  extensions/host/locale/internal.m
  extensions/http/internal.m
  extensions/json/internal.m
  extensions/location/internal.m
  extensions/math/internal.m
  extensions/mouse/internal.m
  extensions/osascript/internal.m
  extensions/pasteboard/internal.m
  extensions/pasteboard/watcher.m
  extensions/plist/internal.m
  extensions/screen/internal.m
  extensions/settings/internal.m
  extensions/socket/internal.m
  extensions/socket/udp.m
  extensions/streamdeck/internal.m
  extensions/timer/internal.m
  extensions/uielement/internal.m
  extensions/urlevent/internal.m
  extensions/usb/internal.m
  extensions/websocket/internal.m
  extensions/window/internal.m
Labels: pr-maintenance

#2713 Fix some build warnings from #2493
  extensions/eventtap/IOHIDEventData.h
  extensions/eventtap/TouchEvents.c
Labels: pr-maintenance

#2715 Make it more clear what the Release Notes preview is
  .github/workflows/pr_release_note_preview.yml
Labels: pr-maintenance

#2716 LuaSkin:checkLuaSkinInstance no longer logs passing checks, to reduce log noise
  LuaSkin/LuaSkin/Skin.m
Labels: pr-maintenance

#2718 Various fixes to get the test suite passing 100% locally
  Hammerspoon Tests/HSapplication.m
  Hammerspoon Tests/HSrequire_all.m
  Hammerspoon Tests/testinit.lua
  Hammerspoon/HSuicore.m
  extensions/audiodevice/test_audiodevice.lua
  extensions/screen/test_screen.lua
Labels: pr-maintenance

#2719 Update app icon to Big Sur style
  Hammerspoon/Images.xcassets/AppIcon.appiconset/1024.png
  Hammerspoon/Images.xcassets/AppIcon.appiconset/128.png
  Hammerspoon/Images.xcassets/AppIcon.appiconset/16.png
  Hammerspoon/Images.xcassets/AppIcon.appiconset/256-1.png
  Hammerspoon/Images.xcassets/AppIcon.appiconset/256.png
  Hammerspoon/Images.xcassets/AppIcon.appiconset/32-1.png
  Hammerspoon/Images.xcassets/AppIcon.appiconset/32.png
  Hammerspoon/Images.xcassets/AppIcon.appiconset/512-1.png
  Hammerspoon/Images.xcassets/AppIcon.appiconset/512.png
  Hammerspoon/Images.xcassets/AppIcon.appiconset/64.png
  Hammerspoon/Images.xcassets/AppIcon.appiconset/Contents.json
  Hammerspoon/Images.xcassets/AppIcon.appiconset/icon_128x128.png
  Hammerspoon/Images.xcassets/AppIcon.appiconset/icon_128x128@2x.png
  Hammerspoon/Images.xcassets/AppIcon.appiconset/icon_16x16.png
  Hammerspoon/Images.xcassets/AppIcon.appiconset/icon_16x16@2x.png
  Hammerspoon/Images.xcassets/AppIcon.appiconset/icon_256x256.png
  Hammerspoon/Images.xcassets/AppIcon.appiconset/icon_256x256@2x.png
  Hammerspoon/Images.xcassets/AppIcon.appiconset/icon_32x32.png
  Hammerspoon/Images.xcassets/AppIcon.appiconset/icon_32x32@2x.png
  Hammerspoon/Images.xcassets/AppIcon.appiconset/icon_512x512.png
  Hammerspoon/Images.xcassets/AppIcon.appiconset/icon_512x512@2x.png
Labels: pr-change

#2712 small fix for hs.window.highlight
  extensions/window/highlight.lua
Labels: pr-fix

#2723 Revert changes to hs.application:isFrontmost()
  Hammerspoon Tests/HSapplication.m
  Hammerspoon/HSuicore.m
Labels: pr-fix

#2722 Maintenance PR Experiment
  .github/workflows/ci_testbuild.yml
Labels: pr-change

#2727 A potential crash in hs.chooser has been guarded against
  extensions/chooser/HSChooser.m
Labels: pr-fix

#2728 Another damaged installation case is now a user-visible error and not a silent crash.
  Hammerspoon/HSLogger.m
  LuaSkin/LuaSkin/Skin.h
  LuaSkin/LuaSkin/Skin.m
Labels: pr-change

#2743 Fix hs.window:snapshot() transparency option. Closes #2742
  extensions/window/internal.m
Labels: pr-fix

#2737 Fix some errors found via Xcode static analysis
  extensions/canvas/internal.m
  extensions/httpserver/internal.m
  extensions/mouse/internal.m
  extensions/window/internal.m
Labels: pr-change

#2734 hs.window:isVisible() will now return false even if the underlying hs.application object is invalid
  extensions/window/init.lua
Labels: pr-fix

#2733 hs.window.desktop() now returns nil if Finder is not running
  extensions/window/init.lua
Labels: pr-fix

#2748 A crash in hs.fs.volume watchers has been guarded against
  extensions/fs/volume.m
Labels: pr-fix

#2751 A crash in hs.webview is now guarded by an experimental protection method
  LuaSkin/LuaSkin/Skin.m
  extensions/eventtap/internal.m
  extensions/timer/internal.m
  extensions/webview/internal.m
  extensions/webview/webview.h
Labels: pr-fix

#2754 A crash bug in hs.settings was fixed. [#2753](https://github.com/Hammerspoon/hammerspoon/issues/2753)
  extensions/settings/internal.m
Labels: pr-fix

#2760 Additional runtime error detection options are now enabled.
  Hammerspoon.xcworkspace/xcshareddata/xcschemes/Release.xcscheme
Labels: pr-maintenance

#2758 All Lua assert()ions are now enabled, and redirected to NSCAssert() for improved capture/logging
  LuaSkin/LuaSkin.xcodeproj/project.pbxproj
Labels: pr-maintenance

#2764 hs.itunes now works correctly on macOS 11
  extensions/itunes/init.lua
Labels: pr-fix

#2773 Updated Sentry crash reporter to 6.2.1
  Podfile
  Podfile.lock
  Pods/Local Podspecs/Sentry.podspec.json
  Pods/Manifest.lock
  Pods/Sentry/Sources/Sentry/SentryClient.m
  Pods/Sentry/Sources/Sentry/SentryFrameRemover.m
  Pods/Sentry/Sources/Sentry/SentryMeta.m
  Pods/Sentry/Sources/Sentry/SentryOptions.m
  Pods/Sentry/Sources/Sentry/SentryStacktraceBuilder.m
  Pods/Sentry/Sources/Sentry/include/SentryFrameRemover.h
  Pods/Sentry/Sources/Sentry/include/SentryStacktraceBuilder.h
  Pods/Sentry/Sources/SentryCrash/Recording/Tools/SentryCrashCPU_arm64.c
Labels: pr-maintenance

#2771 A possible crash relating to a startup error is now detected and logged, pending more information
  Hammerspoon/MJLua.m
  LuaSkin/LuaSkin/Skin.m
Labels: pr-change

#2765 Added an isData optional parameter to hs.websocket:send()
  extensions/websocket/internal.m
Labels: pr-feature

#2767 Fixed potential crash in hs.serial when reloading Hammerspoon
  Hammerspoon Tests/HSserial.m
  Hammerspoon.xcodeproj/project.pbxproj
  extensions/serial/internal.m
  extensions/serial/test_serial.lua
Labels: pr-fix

#2772 A potential crash relating to hs.eventtap callback return value type errors, has been guarded against.
  extensions/eventtap/internal.m
Labels: pr-fix

#2780 Add hs.audiodevice.defaultEffectDevice() and hs.audiodevice:setDefaultEffectDevice()
  Hammerspoon Tests/HSaudiodevice.m
  extensions/audiodevice/internal.m
  extensions/audiodevice/test_audiodevice.lua
Labels: pr-feature

#2781 Remove debug prints(). Closes #2777
  extensions/eventtap/init.lua
Labels: pr-maintenance

#2782 Add docstrings parameter hygiene linting to build_docs.py. Closes #2774
  .github/workflows/ci_testbuild.yml
  Hammerspoon/MJLua.m
  extensions/application/init.lua
  extensions/axuielement/axtextmarker.m
  extensions/axuielement/init.lua
  extensions/axuielement/internal.m
  extensions/axuielement/observer.m
  extensions/bonjour/service.m
  extensions/canvas/init.lua
  extensions/canvas/internal.m
  extensions/chooser/init.lua
  extensions/console/init.lua
  extensions/console/internal.m
  extensions/drawing/init.lua
  extensions/eventtap/internal.m
  extensions/expose/init.lua
  extensions/fs/init.lua
  extensions/geometry/init.lua
  extensions/grid/init.lua
  extensions/hid/init.lua
  extensions/http/init.lua
  extensions/location/init.lua
  extensions/math/init.lua
  extensions/menubar/init.lua
  extensions/midi/internal.m
  extensions/mouse/init.lua
  extensions/network/configurationinternal.m
  extensions/network/init.lua
  extensions/network/ping/init.lua
  extensions/network/ping/internal.m
  extensions/network/reachabilityinternal.m
  extensions/notify/init.lua
  extensions/notify/internal.m
  extensions/screen/init.lua
  extensions/screen/internal.m
  extensions/serial/internal.m
  extensions/settings/internal.m
  extensions/sharing/internal.m
  extensions/speech/internal.m
  extensions/speech/listener.m
  extensions/spoons/init.lua
  extensions/spotlight/internal.m
  extensions/streamdeck/internal.m
  extensions/styledtext/internal.m
  extensions/timer/init.lua
  extensions/watchable/init.lua
  extensions/webview/init.lua
  extensions/webview/internal.m
  extensions/webview/toolbar.lua
  extensions/webview/toolbar_internal.m
  extensions/window/filter.lua
  extensions/window/init.lua
  extensions/window/internal.m
  extensions/window/tiling.lua
  scripts/docs/bin/build_docs.py
  scripts/github-ci-docs.sh
  scripts/github-ci-testbuild.sh
Labels: pr-maintenance

#2779 Fixed regression in hs.json which meant it sometimes returned a string instead of a table
  extensions/json/internal.m
Labels: pr-fix

#2786 A possible crash in hs.webview:evaluateJavaScript() is fixed
  extensions/webview/internal.m
Labels: pr-fix

#2787 A possible crash in hs.task has been guarded against
  extensions/task/internal.m
Labels: pr-fix

#2788 Add LuaSkin checkLuaSkinInstance protection to hs.webview:evaluateJavaScript() callback. Relates to #2786"
  extensions/webview/internal.m
Labels: pr-maintenance
