Repository Hammerspoon/hammerspoon, pull requests merged in 2021-04, with the labels that each got.

#2810 Add links directly to HS source, to the generated docs
  scripts/docs/bin/build_docs.py
  scripts/docs/templates/module.j2.html
Labels: pr-maintenance

#2798 Use the system-configured version of Python 3 when building
  CONTRIBUTING.md
  scripts/docs/bin/build_docs.py
Labels: pr-maintenance

#2792 Disable clang runtime error checkers. Closes #2775
  Hammerspoon.xcworkspace/xcshareddata/xcschemes/Release.xcscheme
Labels: pr-maintenance

#2819 A potential crash in hs.screenRecordingState() was fixed
  Hammerspoon/MJLua.m
Labels: pr-fix

#2800 Add hs.screen example for finding Built-in Retina Display
  extensions/screen/init.lua
Labels: pr-maintenance

#2799 hs.alert.showWithImage()
  extensions/alert/init.lua
Labels: pr-feature

#2830 hs.json functions now work when called from a Lua coroutine
  extensions/json/internal.m
Labels: pr-fix

#2832 hs.urlevent callback now receives the sender's PID where possible
  Hammerspoon/MJAppDelegate.h
  Hammerspoon/MJAppDelegate.m
  extensions/urlevent/init.lua
  extensions/urlevent/internal.m
Labels: pr-change

#2838 Ensure Lua conversion functions are static where possible. Closes #2836
  extensions/bonjour/internal.m
  extensions/bonjour/service.m
  extensions/ipc/internal.m
  extensions/location/internal.m
  extensions/midi/internal.m
  extensions/network/ping/internal.m
  extensions/notify/internal.m
  extensions/serial/internal.m
  extensions/sharing/internal.m
  extensions/webview/datastore.m
  extensions/wifi/watcher.m
Labels: pr-maintenance

#2837 If hs.loadSpoon() is called twice for the same Spoon, the second call will now return the first spoon object instead of reloading it
  extensions/_coresetup/init.lua
Labels: pr-change

#2829 Add LuaSkin instance checking to several extensions
  LuaSkin/LuaSkin/Skin.m
  extensions/audiodevice/internal.m
  extensions/battery/watcher.m
  extensions/network/configurationinternal.m
  extensions/network/hostinternal.m
  extensions/network/reachabilityinternal.m
  extensions/pathwatcher/internal.m
  extensions/usb/watcher.m
Labels: pr-maintenance

#2845 AddressSanitiser noticed that we're accessing uninitialised memory when retrieving luaSkinUUID strings. Explicitly memset() it to '\0'
  extensions/audiodevice/internal.m
  extensions/battery/watcher.m
  extensions/eventtap/internal.m
  extensions/network/configurationinternal.m
  extensions/network/hostinternal.m
  extensions/network/reachabilityinternal.m
  extensions/pathwatcher/internal.m
  extensions/usb/watcher.m
Labels: pr-maintenance

#2846 hs.location.geocoder.lookupAddress() should no longer crash in some circumstances.
  extensions/location/internal.m
Labels: pr-fix

#2852 hs.crash.crashKV() no longer overwrites all existing key/value pairs
  extensions/crash/internal.m
Labels: pr-fix

#2854 Keep MJLuaLogDelegate minimally existant so we can log breadcrumbs of lua_State lifecycle
  Hammerspoon/MJLua.m
Labels: pr-maintenance
