Repository Hammerspoon/hammerspoon, pull requests merged in 2022-11, with the labels that each got.

#3279 hs.http must follow redirects #1889
  Hammerspoon Tests/HShttp.m
  Hammerspoon.xcodeproj/project.pbxproj
  extensions/http/libhttp.m
  extensions/http/test_http.lua
Labels: pr-feature

#3311 Slight arg parsing tweak to #3279
  extensions/http/libhttp.m
Labels: pr-fix

#3314 Added hs.serial:rts() and hs.serial:dtr()
  extensions/serial/libserial.m
Labels: pr-feature

#3317 Switch to using webhooks for IRC notifications
  .github/workflows/ci_nightly.yml
  .github/workflows/ci_testbuild.yml
Labels: pr-maintenance

#3298 feat(spaces): add force arg for moveWindowToSpace
  extensions/spaces/libspaces.m
Labels: pr-feature
