Repository Hammerspoon/hammerspoon, pull requests merged in 2022-07, with the labels that each got.

#3196 [READY] Fix hs.spaces so it works when hs.spaces.screensHaveSeparateSpaces() is false
  extensions/spaces/spaces.lua
Labels: bug, enhancement, pr-fix

#3211 Fix two crash bugs in hs.camera
  extensions/camera/libcamera.m
Labels: pr-fix

#3228 Reformat documentation for hs.socket and hs.socket.udp
  extensions/socket/libsocket.m
  extensions/socket/libsocket_udp.m
  extensions/socket/socket.lua
Labels: pr-maintenance

#3236 add DemoPro to SKIP_APPS_TRANSIENT_WINDOWS
  extensions/window/window_filter.lua
Labels: pr-fix

#3238 fix bug where window switcher does not go away when caps lock is on
  extensions/window/window_switcher.lua
Labels: pr-fix

#3242 fix typo
  extensions/_coresetup/_coresetup.lua
Labels: pr-fix
