Repository Hammerspoon/hammerspoon, pull requests merged in 2022-02, with the labels that each got.

#3105 fix typo
  extensions/drawing/color/drawing_color.lua
Labels: pr-maintenance

#3119 Fix crash in hs.serial.deviceCallback(). Closes #3118
  extensions/serial/libserial.m
Labels: pr-fix

#3123 Fix hs.mouse test for devices being internal or not. Closes #3112
  extensions/mouse/libmouse.m
Labels: pr-fix

#3122 Improve hs.ipc safety
  extensions/ipc/cli/hs.m
Labels: pr-fix

#3125 Add hs.http.put() and hs.http.asyncPut(). Closes #3107
  extensions/http/http.lua
Labels: pr-feature

#3131 Work around macOS12 including two new keycodes in keyboard layout data, seemingly incorrectly. Closes #2980
  extensions/keycodes/libkeycodes.m
Labels: pr-fix
