Repository Hammerspoon/hammerspoon, pull requests merged in 2022-03, with the labels that each got.

#3134 Add LSGCCanary support to hs.streamdeck
  LuaSkin/LuaSkin/Skin.m
  extensions/streamdeck/HSStreamDeckDevice.h
  extensions/streamdeck/HSStreamDeckDevice.m
  extensions/streamdeck/HSStreamDeckManager.h
  extensions/streamdeck/HSStreamDeckManager.m
  extensions/streamdeck/libstreamdeck.m
Labels: pr-fix

#3136 Fix two code analysis issues that Xcode identified
  Hammerspoon/HSuicore.m
  Hammerspoon/MJLua.m
Labels: pr-maintenance

#3144 Canary mismatches are no longer fatal exceptions, they simply return the correct value so their callers can abandon work.
  LuaSkin/LuaSkin/Skin.m
Labels: pr-maintenance

#3139 feat: extra lua runtime lookup paths
  Hammerspoon/setup.lua
Labels: pr-feature

#3155 Add LuaSkin GC Canary to hs.webview fadeOut method. Closes #3148
  extensions/webview/libwebview.m
Labels: pr-fix

#3160 Remove hard-coded architecture build setting from Cocoapods-generated xcodeproj
  Podfile
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
Labels: pr-maintenance

#3165 Fix hs.http callback crashes with Lua coroutines
  extensions/http/libhttp.m
Labels: pr-fix

#3164 Add hs.screen:getInfo()
  extensions/screen/libscreen.m
Labels: pr-feature

#3169 Removed hs.canvas:delete() from hs.alert
  extensions/alert/alert.lua
Labels: pr-fix

#3167 Add C->Lua safety checks to hs.canvas fadeOut:andDelete:withState
  extensions/canvas/libcanvas.m
Labels: pr-fix

#3172 Fix hs.menubar image positioning and add hs.menubar:imagePosition()
  extensions/menubar/libmenubar.m
  extensions/menubar/menubar.lua
Labels: pr-fix
