Repository Hammerspoon/hammerspoon, pull requests merged in 2023-12, with the labels that each got.

#3440 [Ready] hs.watchable -- added alwaysNotify to watcher
  extensions/watchable/watchable.lua
Labels: pr-feature

#3449 [READY] hs.battery -- Fix for systems that report an empty array for powerSources
  extensions/battery/battery.lua
Labels: pr-fix

#3475 Remove warnings from canvas and toolbar
  extensions/canvas/libcanvas.m
  extensions/webview/libwebview_toolbar.m
Labels: pr-maintenance

#3476 Include docs.css in build for built in web help
  Hammerspoon.xcodeproj/project.pbxproj
  extensions/doc/html_blocks.h
Labels: pr-fix

#3483 Rewrite of hs.hash to simplify adding new hashes
  Hammerspoon.xcodeproj/project.pbxproj
  extensions/fs/fs.lua
  extensions/fs/libfs.m
  extensions/hash/algorithms.h
  extensions/hash/algorithms.m
  extensions/hash/byte_order.h
  extensions/hash/hash.lua
  extensions/hash/libhash.m
  extensions/hash/sha3.h
  extensions/hash/sha3.m
Labels: pr-change

#3492 hs.hotkey: add help for setLogLevel and getLogLevel
  extensions/hotkey/hotkey.lua
Labels: docs, pr-maintenance

#3504 Fixed mistake in build_docs.py for markdown creation
  scripts/docs/bin/build_docs.py
Labels: pr-maintenance

#3542 Update alert.lua: allow window object as parameter
  extensions/alert/alert.lua
Labels: pr-feature

#3546 Add getCurrentTrackArtworkURL() to spotify extension
  extensions/spotify/spotify.lua
Labels: pr-feature
