Repository Hammerspoon/hammerspoon, pull requests merged in 2023-03, with the labels that each got.

#3407 Add hs.streamdeck:imageSize()
  extensions/streamdeck/libstreamdeck.m
Labels: pr-feature

#3409 Add support for Stream Deck Pedal
  Hammerspoon.xcodeproj/project.pbxproj
  extensions/streamdeck/HSStreamDeckDevicePedal.h
  extensions/streamdeck/HSStreamDeckDevicePedal.m
  extensions/streamdeck/HSStreamDeckManager.h
  extensions/streamdeck/HSStreamDeckManager.m
  extensions/streamdeck/streamdeck.h
  extensions/streamdeck/streamdeck.lua
Labels: pr-feature

#3237 speedup window switching timers
  extensions/window/window_switcher.lua
Labels: pr-change

#3413 Actually complete setting macOS deployment target to 11.0
  LuaSkin/LuaSkin-Base.xcconfig
  Podfile
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
Labels: pr-maintenance

#3414 Force hs.timer to use main CFRunLoop, even though it likely already was
  extensions/timer/libtimer.m
Labels: pr-maintenance

#3412 Fix various things found by Xcode analyser
  Hammerspoon/MJLua.m
  Hammerspoon/MJMenuIcon.m
  extensions/chooser/HSChooserVerticallyCenteringTextFieldCell.m
  extensions/console/libconsole.m
  extensions/image/libimage.m
  extensions/websocket/libwebsocket.m
Labels: pr-maintenance

#3419 Fix ICMP socket leak in hs.ping
  extensions/network/ping/SimplePing.m
Labels: pr-fix

#3428 Add binary hash functions to hs.hash
  extensions/hash/libhash.m
Labels: pr-feature
