Repository Hammerspoon/hammerspoon, pull requests merged in 2024-08, with the labels that each got.

#3638 [Review] Fix moving window to space in Sonoma 14.5
  extensions/spaces/libspaces.m
  extensions/spaces/private.h
  extensions/spaces/spaces.lua
Labels: pr-fix

#3657 Improve preferences resetting dialog
  Hammerspoon/MJAppDelegate.m
Labels: pr-feature

#3659 Improve Console window performance and RAM usage
  Hammerspoon/ConsoleWindow.xib
  Hammerspoon/MJConsoleWindowController.m
Labels: pr-fix

#3664 Validate that all arguments provided for an hs.task, are strings
  extensions/task/libtask.m
Labels: pr-fix

#3667 Lua skin additions
  LuaSkin/LuaSkin/Skin.h
  LuaSkin/LuaSkin/Skin.m
Labels: enhancement, pr-feature
